# Generated by Django 3.2 on 2021-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='اسم غذا')),
                ('description', models.TextField(help_text='در اینجا میتوانید توضیحات کاملی از غذا ارائه کنید', verbose_name='توضیحات کامل غذا')),
                ('cover', models.ImageField(help_text='در اینجا میتوانید عکس محصول را برای جذب مشتری آپلود کنید', upload_to='uploads/images', verbose_name='عکس غذا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('pointByCheif', models.IntegerField(help_text='در اینجا نمره آشپز را وارد نمایید', verbose_name='نمره آشپز')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
                'ordering': ['price'],
            },
        ),
    ]
