# Generated by Django 3.2 on 2021-05-03 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='در اینجا میتونید نظرتون رو وارد کنید', verbose_name='نظر')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='اسم غذا')),
                ('description', models.TextField(help_text='در اینجا میتوانید توضیحات کاملی از غذا ارائه کنید', verbose_name='توضیحات کامل غذا')),
                ('cover', models.ImageField(help_text='در اینجا میتوانید عکس محصول را برای جذب مشتری آپلود کنید', upload_to='uploads/images/foods', verbose_name='عکس غذا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('pointByCheif', models.IntegerField(help_text='در اینجا نمره آشپز را وارد نمایید', verbose_name='نمره آشپز')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(to='resturant.Comments', verbose_name='نظرات')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
            },
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='در اینجا اسم رستوران را وارد کنید', max_length=150, verbose_name='اسم رستوران')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='لینک رستوران')),
                ('cover', models.ImageField(help_text='در اینجا میتوانید عکسی برای دیده شدن بهتر رستورانتان بگذارید', upload_to='uploads/images/resturants', verbose_name='عکس رستوران')),
                ('descriptions', models.TextField(help_text='در اینجا میتوانید درباره رستوران خود اطلاعاتی را وارد کنید', verbose_name='درباره رستوران')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('resturant_foods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resturant.foods', verbose_name='غذا ها')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='عنوان سفارش')),
                ('timeDelay', models.IntegerField(blank=True, verbose_name='تایمر سفارش')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('foods', models.ManyToManyField(to='resturant.Foods', verbose_name='غذا های سفارش شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-timeDelay'],
            },
        ),
        migrations.AddField(
            model_name='foods',
            name='foods_resturant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant', verbose_name='رستورانی که این غذا را پخت میکند'),
        ),
        migrations.AddIndex(
            model_name='resturant',
            index=models.Index(fields=['name'], name='name_resturant_idx'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='foods',
            order_with_respect_to='foods_resturant',
        ),
    ]
